carts/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.cart, name="cart"),
    path("add_cart/<int:product_id>/", views.add_cart, name="add_cart"),
    path(
        "remove_cart/<int:product_id>/<int:cart_item_id>/",
        views.remove_cart,
        name="remove_cart",
    ),
    path(
        "remove_cart_item/<int:product_id>/<int:cart_item_id>/",
        views.remove_cart_item,
        name="remove_cart_item",
    ),
    path("checkout/", views.checkout, name="checkout"),
]

jmkart/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name="home"),
    path("store/", include("store.urls")),
    path("cart/", include("carts.urls")),
    path("accounts/", include("accounts.urls")),
    path("orders/", include("orders.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


# =====================================

# from django.contrib import admin
# from django.urls import path, include
# from . import views
# from django.conf.urls.static import static
# from django.conf import settings

# urlpatterns = [
#     path("admin/", admin.site.urls),
#     path("", views.home, name="home"),
#     path("store/", include("store.urls")),
#     path("cart/", include("carts.urls")),
#     path("accounts/", include("accounts.urls")),
#     # ORDERS
#     path("orders/", include("orders.urls")),
# ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.store, name='store'),
    path('category/<slug:category_slug>/', views.store, name='products_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>/', views.product_detail, name='product_detail'),
    path('search/', views.search, name='search'),
    path('submit_review/<int:product_id>/', views.submit_review, name='submit_review'), # type: ignore
]

store/models.py
from django.db import models
from category.models import Category
from django.urls import reverse
from accounts.models import Account
from django.db.models import Avg, Count

# Create your models here.

class Product(models.Model):
  product_name  = models.CharField(max_length=200, unique=True)
  slug          = models.SlugField(max_length=200, unique=True)
  description   = models.TextField(max_length=500, blank=True)
  price         = models.IntegerField()
  images        = models.ImageField(upload_to='photos/products')
  stock         = models.IntegerField()
  is_available  = models.BooleanField(default=True)
  category      = models.ForeignKey(Category, on_delete=models.CASCADE)
  created_date  = models.DateTimeField(auto_now_add=True)
  modified_date = models.DateTimeField(auto_now=True)

  def get_url(self):
    return reverse('product_detail', args=[self.category.slug, self.slug])

  def __str__(self):
      return self.product_name

  def averageReview(self):
      reviews = ReviewRating.objects.filter(
          product=self,
          status=True
      ).aggregate(avg_rating=Avg('rating'))

      avg = reviews['avg_rating']
      if avg is None:
          return 0
      return round(float(avg), 1)

  def countReview(self):
      reviews = ReviewRating.objects.filter(
          product=self,
          status=True
      ).aggregate(count=Count('id'))

      count = reviews.get('count')
      if count is None:
          return 0
      return int(count)



class VariationManager(models.Manager):
  def colors(self):
    return super(VariationManager, self).filter(variation_category='color', is_active=True)

  def sizes(self):
    return super(VariationManager, self).filter(variation_category='size', is_active=True)

variation_category_choice = (
  ('color', 'color'),
  ('size', 'size')
)

class Variation(models.Model):
  product = models.ForeignKey(Product, on_delete=models.CASCADE)
  variation_category = models.CharField(max_length=100, choices=variation_category_choice)
  variation_value = models.CharField(max_length=100)
  is_active = models.BooleanField(default=True)
  created_date = models.DateTimeField(auto_now=True)

  objects = VariationManager()

  def __str__(self):
    return self.variation_value

class ReviewRating(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    subject = models.CharField(max_length=100, blank=True)
    review = models.TextField(max_length=500, blank=True)
    rating = models.FloatField()
    ip = models.CharField(max_length=20, blank=True)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject

class ProductGallery(models.Model):
    product = models.ForeignKey(Product, default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='store/products', max_length=255)

    def __str__(self):
        return self.product.product_name

    class Meta:
        verbose_name = 'productgallery'
        verbose_name_plural = 'product gallery'

carts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from store.models import Product, Variation
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse


def cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    current_user = request.user
    product = Product.objects.get(id=product_id)  # get the product

    # Collect product variations (same for both auth and guest)
    product_variation = []
    if request.method == "POST":
        for key, value in request.POST.items():
            try:
                variation = Variation.objects.get(
                    product=product,
                    variation_category__iexact=key,
                    variation_value__iexact=value,
                )
                product_variation.append(variation)
            except Variation.DoesNotExist:
                pass

    # ==========================
    # If the user is authenticated
    # ==========================
    if current_user.is_authenticated:
        is_cart_item_exists = CartItem.objects.filter(
            product=product,
            user=current_user,
        ).exists()

        if is_cart_item_exists:
            cart_items = CartItem.objects.filter(
                product=product,
                user=current_user,
            )
            ex_var_list = []
            id = []
            for item in cart_items:
                existing_variation = item.variations.all()
                ex_var_list.append(list(existing_variation))
                id.append(item.id)  # type: ignore

            if product_variation in ex_var_list:
                # increase the cart item quantity
                index = ex_var_list.index(product_variation)
                item_id = id[index]
                item = CartItem.objects.get(product=product, id=item_id)
                item.quantity += 1
                item.save()
            else:
                # create a new cart item
                item = CartItem.objects.create(
                    product=product,
                    quantity=1,
                    user=current_user,
                )
                if product_variation:
                    item.variations.clear()
                    item.variations.add(*product_variation)
                item.save()
        else:
            cart_item = CartItem.objects.create(
                product=product,
                quantity=1,
                user=current_user,
            )
            if product_variation:
                cart_item.variations.clear()
                cart_item.variations.add(*product_variation)
            cart_item.save()

        return redirect("cart")

    # ==========================
    # If the user is NOT authenticated
    # ==========================
    try:
        cart = Cart.objects.get(cart_id=cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id=cart_id(request))
    cart.save()

    is_cart_item_exists = CartItem.objects.filter(
        product=product,
        cart=cart,
    ).exists()

    if is_cart_item_exists:
        cart_items = CartItem.objects.filter(
            product=product,
            cart=cart,
        )

        ex_var_list = []
        item_ids = []

        for item in cart_items:
            existing_variation = item.variations.all()
            ex_var_list.append(list(existing_variation))
            item_ids.append(item.id)  # type: ignore

        if product_variation in ex_var_list:
            # increase the cart item quantity
            index = ex_var_list.index(product_variation)
            item_id = item_ids[index]
            item = CartItem.objects.get(product=product, id=item_id)
            item.quantity += 1
            item.save()
        else:
            # create a new cart item
            item = CartItem.objects.create(
                product=product,
                quantity=1,
                cart=cart,
            )
            if product_variation:
                item.variations.clear()
                item.variations.add(*product_variation)
            item.save()
    else:
        cart_item = CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart,
        )
        if len(product_variation) > 0:
            cart_item.variations.clear()
            cart_item.variations.add(*product_variation)
        cart_item.save()
    return redirect("cart")


def remove_cart(request, product_id, cart_item_id):

    product = get_object_or_404(Product, id=product_id)
    try:
        if request.user.is_authenticated:
            cart_item = CartItem.objects.get(
                product=product,
                user=request.user,
                id=cart_item_id,
            )
        else:
            cart = Cart.objects.get(cart_id=cart_id(request))
            cart_item = CartItem.objects.get(
                product=product,
                cart=cart,
                id=cart_item_id,
            )
        if cart_item.quantity > 1:
            cart_item.quantity -= 1
            cart_item.save()
        else:
            cart_item.delete()
    except:
        pass
    return redirect("cart")  # type: ignore


def remove_cart_item(request, product_id, cart_item_id):
    product = get_object_or_404(Product, id=product_id)
    if request.user.is_authenticated:
        cart_item = CartItem.objects.get(
            product=product,
            user=request.user,
            id=cart_item_id,
        )
    else:
        cart = Cart.objects.get(cart_id=cart_id(request))
        cart_item = CartItem.objects.get(
            product=product,
            cart=cart,
            id=cart_item_id,
        )
    cart_item.delete()
    return redirect("cart")


def cart(request, total=0, quantity=0, cart_items=None):
    try:
        tax = 0
        grand_total = 0

        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(
                user=request.user,
                is_active=True,
            )
        else:
            cart = Cart.objects.get(cart_id=cart_id(request))
            cart_items = CartItem.objects.filter(
                cart=cart,
                is_active=True,
            )

        for cart_item in cart_items:
            total += cart_item.product.price * cart_item.quantity
            quantity += cart_item.quantity

        tax = (8.875 * total) / 100
        grand_total = total + tax

    except ObjectDoesNotExist:
        pass

    context = {
        "total": total,
        "quantity": quantity,
        "cart_items": cart_items,
        "tax": tax,
        "grand_total": grand_total,
    }

    return render(request, "store/cart.html", context)


# ===============================================================


@login_required(login_url="login")
def checkout(request, total=0, quantity=0, cart_items=None):
    try:
        tax = 0
        grand_total = 0

        # Use the SAME logic as cart() for authenticated users
        # cart_items = CartItem.objects.filter(
        #     user=request.user,
        #     is_active=True,
        # )
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(
                user=request.user,
                is_active=True,
            )
        else:
            cart = Cart.objects.get(cart_id=cart_id(request))
            cart_items = CartItem.objects.filter(
                cart=cart,
                is_active=True,
            )

        for cart_item in cart_items:
            total += cart_item.product.price * cart_item.quantity
            quantity += cart_item.quantity

        tax = (8.875 * total) / 100
        grand_total = total + tax

    except ObjectDoesNotExist:
        pass

    context = {
        "total": total,
        "quantity": quantity,
        "cart_items": cart_items,
        "tax": tax,
        "grand_total": grand_total,
    }
    return render(request, "store/checkout.html", context)

store/views.py
from pyexpat.errors import messages
from django.shortcuts import redirect, render, get_object_or_404

from orders.models import OrderProduct
from .models import Product, ReviewRating, ProductGallery
from category.models import Category
from carts.models import CartItem
from django.db.models import Q

from carts.views import cart_id
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator #(1)
from django.http import HttpResponse
from .forms import ReviewForm
from django.contrib import messages
from orders.models import OrderProduct

# Create your views here.

def store(request, category_slug=None):
    categories = None
    products = None

    if category_slug != None:
        categories = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=categories, is_available=True)
        paginator = Paginator(products, 1)  #(5)
        page = request.GET.get('page')  #(5)
        paged_products = paginator.get_page(page) #(5)
        product_count = products.count()

    else:
        products = Product.objects.all().filter(is_available=True).order_by('id')
        paginator = Paginator(products, 3)  #(2)
        page = request.GET.get('page')  #(3)
        paged_products = paginator.get_page(page) #(4)
        product_count = products.count()


    context = {
    'products': paged_products, #(5)
    'product_count': product_count,
    }
    return render(request, 'store/store.html', context)

def product_detail(request, category_slug, product_slug):
    single_product = get_object_or_404(
        Product,
        category__slug=category_slug,
        slug=product_slug
    )

    in_cart = CartItem.objects.filter(
        cart__cart_id=cart_id(request),
        product=single_product
    ).exists()

    orderproduct = False
    if request.user.is_authenticated:
        orderproduct = OrderProduct.objects.filter(
            user_id=request.user.id,
            product_id=single_product.id, # type: ignore
        ).exists()

    # Getting the reviews
    reviews = ReviewRating.objects.filter(product_id=single_product.id, status=True)  # type: ignore # turn False if you don't want review to show

    # Get the product gallery
    product_gallery = ProductGallery.objects.filter(product_id=single_product.id) # type: ignore

    context = {
        "single_product": single_product,
        "in_cart": in_cart,
        "orderproduct": orderproduct,
        'reviews': reviews,
        'product_gallery': product_gallery,
    }
    return render(request, "store/product_detail.html", context)

def search(request):
  if 'keyword' in request.GET:
    keyword = request.GET['keyword']
    if keyword:
      products = Product.objects.order_by('created_date').filter(Q(description__icontains=keyword) | Q(product_name__icontains=keyword))
      product_count = products.count()
  context = {
    'products': products,
    'product_count': product_count,
  }
  return render(request, 'store/store.html', context)


def submit_review(request, product_id):
    url = request.META.get('HTTP_REFERER')
    if request.method == 'POST':
        try:
            reviews = ReviewRating.objects.get(user__id=request.user.id, product__id=product_id)
            form = ReviewForm(request.POST, instance=reviews)
            form.save()
            messages.success(request, 'Thank you! Your review has been updated.') # type: ignore
            return redirect(url)
        except ReviewRating.DoesNotExist:
            form = ReviewForm(request.POST)
            if form.is_valid():
                data = ReviewRating()
                data.subject = form.cleaned_data['subject']
                data.rating = form.cleaned_data['rating']
                data.review = form.cleaned_data['review']
                data.ip = request.META.get('REMOTE_ADDR')
                data.product_id = product_id # type: ignore
                data.user_id = request.user.id # type: ignore
                data.save()
                messages.success(request, 'Thank you! Your review has been submitted.')  # type: ignore
                return redirect(url)

templates/store/product_detail.html
{% extends "base.html" %}
{% load rating_tags %}
{% load static %}
{% block content %}
  <section class="section-content padding-y bg">
    <div class="container">
      <!-- ============================ COMPONENT 1 ================================= -->
      <div class="card">
        <div class="row no-gutters">
          <aside class="col-md-6">
            <article class="gallery-wrap">
              <div class="img-big-wrap mainImage">
                <center><img src="{{ single_product.images.url }}" alt="Product Image"></center>
              </div>
            </article>

            <ul class="thumb">
              {% for i in product_gallery %}
                <li>
                  <a href="{{ i.image.url }}">
                    <img src="{{ i.image.url }}" alt="Product Image">
                  </a>
                </li>
              {% endfor %}
            </ul>

          </aside>
          <main class="col-md-6 border-left">

            <form action="{% url 'add_cart' single_product.id %}" method="POST">
              {% csrf_token %}
              <article class="content-body">

                <h2 class="title">{{ single_product.product_name }}</h2>
                <div class="rating-star">
                  <span>
                    <i class="fa fa-star{% if single_product.averageReview < 0.5 %}-o{% elif single_product.averageReview < 1 %}-half-o{% endif             %}"></i>
                    <i class="fa fa-star{% if single_product.averageReview < 1.5 %}-o{% elif single_product.averageReview < 2 %}-half-o{% endif             %}"></i>
                    <i class="fa fa-star{% if single_product.averageReview < 2.5 %}-o{% elif single_product.averageReview < 3 %}-half-o{% endif             %}"></i>
                    <i class="fa fa-star{% if single_product.averageReview < 3.5 %}-o{% elif single_product.averageReview < 4 %}-half-o{% endif             %}"></i>
                    <i class="fa fa-star{% if single_product.averageReview < 4.5 %}-o{% elif single_product.averageReview < 5 %}-half-o{% endif             %}"></i>
                    <span>{{ single_product.countReview }} reviews</span>
                  </span>
                  <br>
                  <br>
                </div>
                <div class="mb-3">
                  <var class="price h4">$ {{ single_product.price }}</var>
                </div>
                <p>{{ single_product.description }}</p>
                <hr>
                <div class="row">
                  <div class="item-option-select">
                    <h6>Choose Color</h6>
                    <select name="color" class="form-control" required>
                      <option value="" disable selected>Select</option>
                      {% for i in single_product.variation_set.colors %}
                        <option value="{{ i.variation_value | lower }}">{{ i.variation_value | capfirst }}</option>
                      {% endfor %}
                    </select>
                  </div>
                </div>
                <!-- row.// -->
                <div class="row">
                  <div class="item-option-select">
                    <h6>Select Size</h6>
                    <select name="size" class="form-control">
                      <option value="" disable selected>Select</option>
                      {% for i in single_product.variation_set.sizes %}
                        <option value="{{ i.variation_value | lower }}">{{ i.variation_value | capfirst }}</option>
                      {% endfor %}
                    </select>
                  </div>
                </div>
                <!-- row.// -->
                <hr>
                {% if single_product.stock <= 0 %}
                  <h5 class="text-danger">Out of Stock</h5>
                {% else %}
                  <button type="submit" class="btn btn-primary">
                    <span class="text">Add to cart</span>
                    <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                  </button>
                {% endif %}
              </article> <!-- product-info-aside .// -->
            </form>
          </main>
          <!-- col.// -->
        </div>
        <!-- row.// -->
      </div>
      <!-- card.// -->
      <!-- ============================ COMPONENT 1 END .// ================================= -->
      <br>
      <div class="row">
        <div class="col-md-9">


          <form action="{% url 'submit_review' single_product.id %}" method="POST">
            {% csrf_token %}
            <h5>Write Your Review</h5>

            <div>
              <!-- Rating Stars -->

              <label class="mb-2">How do you rate this product?</label>
              <br>

              <div class="rate">
                <input type="radio" name="rating" id="star5" value="5" required />
                <label for="star5" title="5 stars"></label>

                <input type="radio" name="rating" id="star4half" value="4.5" />
                <label for="star4half" class="half" title="4.5 stars"></label>

                <input type="radio" name="rating" id="star4" value="4" />
                <label for="star4" title="4 stars"></label>

                <input type="radio" name="rating" id="star3half" value="3.5" />
                <label for="star3half" class="half" title="3.5 stars"></label>

                <input type="radio" name="rating" id="star3" value="3" />
                <label for="star3" title="3 stars"></label>

                <input type="radio" name="rating" id="star2half" value="2.5" />
                <label for="star2half" class="half" title="2.5 stars"></label>

                <input type="radio" name="rating" id="star2" value="2" />
                <label for="star2" title="2 stars"></label>

                <input type="radio" name="rating" id="star1half" value="1.5" />
                <label for="star1half" class="half" title="1.5 stars"></label>

                <input type="radio" name="rating" id="star1" value="1" />
                <label for="star1" title="1 star"></label>

                <input type="radio" name="rating" id="starhalf" value="0.5" />
                <label for="starhalf" class="half" title="0.5 stars"></label>
              </div>
              <br>

              Review Title:
              <input type="text" class="form-control" name="subject">
              <br>
              Review:
              <textarea name="review" rows="4" class="form-control"></textarea>
              <br>

              {% if user.is_authenticated %}
                {% if orderproduct %}
                  <input type="submit" value="Submit Review" class="btn btn-primary">
                {% else %}
                  <p>You must purchase this product to post a review.</p>
                {% endif %}
              {% else %}
              <p>You must be logged in to post a review. <span><a href="{% url 'login' %}">Login now</a></span></p>
              {% endif %}

            </div>

            {% include "includes/alerts.html" %}

          </form>
          <br>

          <header class="section-heading">
            <h3>Customer Reviews</h3>
            <div class="rating-star">
              <span>
                <i class="fa fa-star{% if single_product.averageReview < 0.5 %}-o{% elif single_product.averageReview < 1 %}-half-o{% endif %}"></i>
                <i class="fa fa-star{% if single_product.averageReview < 1.5 %}-o{% elif single_product.averageReview < 2 %}-half-o{% endif %}"></i>
                <i class="fa fa-star{% if single_product.averageReview < 2.5 %}-o{% elif single_product.averageReview < 3 %}-half-o{% endif %}"></i>
                <i class="fa fa-star{% if single_product.averageReview < 3.5 %}-o{% elif single_product.averageReview < 4 %}-half-o{% endif %}"></i>
                <i class="fa fa-star{% if single_product.averageReview < 4.5 %}-o{% elif single_product.averageReview < 5 %}-half-o{% endif %}"></i>
                <span>{{ single_product.countReview }} reviews</span>
              </span>
            </div>

          </header>

          {% for review in reviews %}
          <article class="box mb-3">
            <div class="icontext w-100">

              <div class="text">
                <span class="date text-muted float-md-right">{{ review.updated_at }}</span>
                <h6 class="mb-1">{{ review.user.full_name }}</h6>
                <div class="rating-star">
                  <span>
                    <i class="fa fa-star{% if review.rating < 0.5 %}-o{% elif review.rating < 1 %}-half-o{% endif %}"></i>
                    <i class="fa fa-star{% if review.rating < 1.5 %}-o{% elif review.rating < 2 %}-half-o{% endif %}"></i>
                    <i class="fa fa-star{% if review.rating < 2.5 %}-o{% elif review.rating < 3 %}-half-o{% endif %}"></i>
                    <i class="fa fa-star{% if review.rating < 3.5 %}-o{% elif review.rating < 4 %}-half-o{% endif %}"></i>
                    <i class="fa fa-star{% if review.rating < 4.5 %}-o{% elif review.rating < 5 %}-half-o{% endif %}"></i>
                  </span>
                </div>

              </div>
            </div>
            <!-- icontext.// -->
            <div class="mt-3">
              <h6>{{ review.subject }}</h6>
              <p>
                {{ review.review }}
              </p>
            </div>
          </article>
          {% endfor %}

        </div>
        <!-- col.// -->
      </div>
      <!-- row.// -->
    </div>
    <!-- container .//  -->
  </section>
  <!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock %}